Semi-automatic implemenation of #250
wlmac/metropolis pull request #273
Opened 2024-08-27 17:49 UTC by pinwheeeel

#250 

Not fully automatic because it's not possible to assign organizations to events without doing it manually. Link to the calendar is controlled in django settings (SECRET_GCAL_ADDRESS).
lmk if you have questions

2024-08-28 02:54 UTC, JasonLovesDoggo requested changes
This looks great!!! (not tested)

Just a few tiny tweaks

2024-08-28 02:54 UTC, JasonLovesDoggo commented on core/management/commands/add_clubs.py
> +        if expected_header != next(csv_reader):
same thing but 👍

2024-08-28 02:54 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +https://imgur.com/a/kC62n5p
want to also upload this somewhere internally as imgur does take stuff down

2024-08-28 02:54 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +                term_override = Term.objects.get(name__iexact=options["term"])
iirc there can be duplicates, want to use ids?

2024-08-28 02:54 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +            except Term.DoesNotExist:
or you can do except Term.MultipleObjectsReturned then ask for ID

2024-08-28 02:54 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +            raise AssertionError("SECRET_GCAL_ADDRESS is not set. Please change in metropolis/settings.py")
it should be changed in local_settings.py 

and maybe link how to get it

2024-09-01 02:12 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +                    "schedule_format": "default",
would you still be able to add late start/other events this way? A  good number of events change the schedule format

2024-09-01 04:14 UTC, pinwheeeel commented on core/management/commands/add_events.py
> +                    "schedule_format": "default",
yes, "default" is just a placeholder for the default schedule format since it's semantically guaranteed to exist and it's going to be the most likely one anyways

2024-09-01 04:25 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +                    "schedule_format": "default",
awesome! 

Okay so i'm just waiting for my comment about MultipleObjectsReturned

2024-09-01 04:43 UTC, pinwheeeel commented on core/management/commands/add_events.py
> +                    "schedule_format": "default",
I've slightly changed (overengineered) the way Term is obtained. If a cli argument is provided, it tries search for name and uses id as MultipleObjects fallback and uses that for everything. Otherwise it uses event date to find a corresponding term, but will also use name and then id as fallback

I'll do one more rigorous test tomorrow and then figure out the imgur links

2024-09-01 22:06 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> +                    "schedule_format": "default",
sounds good! Ping me on discord once it's done and I'll do one final review then you can merge it!

2024-09-04 01:06 UTC, JasonLovesDoggo requested changes

2024-09-04 01:06 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> -                        # TODO: parse rrule
LOL I do not blame you...

2024-09-04 01:06 UTC, JasonLovesDoggo commented on core/management/commands/add_events.py
> -                        # TODO: parse rrule
maybe just print something out if there IS an rrule

2024-09-04 01:08 UTC, JasonLovesDoggo approved these changes
Just do that small 1 line print statement and you can merge!

2024-09-04 19:14 UTC, merged