Faster Way To Add Late Starts
wlmac/metropolis pull request #285
Opened 2024-11-02 18:57 UTC by imaegg11

Faster way to create late starts through a form under events at /admin/core/event/createLateStart/. Currently the only way to access the form is by typing out the url, which needs to be changed but I am not sure where to make the form accessible from. The form does redirect the user to the events page after a successful creation of a late start event. 

Screenshot of the form:
![image](https://github.com/user-attachments/assets/c4c5da9c-c05c-466d-b448-708fc7c0690b)

2024-11-02 19:00 UTC, JasonLovesDoggo commented
No need to have the organization field as that will always be set to school, what you can do though is check if school exists and if not then create it

2024-11-02 19:00 UTC, JasonLovesDoggo commented
No need to have the organization field as that will always be set to school, what you can do though is check if school exists and if not then create it

2024-11-02 19:02 UTC, JasonLovesDoggo requested changes
Lastly, how would you access this form without direct url

2024-11-02 19:02 UTC, JasonLovesDoggo commented on core/models/course.py
> +        if self.start_date != None and self.end_date != None and self.start_date > self.end_date:
Reason for changing this?

2024-11-02 19:08 UTC, imaegg11 commented on core/models/course.py
> +        if self.start_date != None and self.end_date != None and self.start_date > self.end_date:
Was mildly annoying me when testing some things. This change can 100% be dropped.

2024-11-02 19:20 UTC, JasonLovesDoggo commented on core/models/course.py
> +        if self.start_date != None and self.end_date != None and self.start_date > self.end_date:
Well there should never be an event without a start/end date set. that is enforced both on the model both by the super().clean() and on the database level.

2024-11-02 19:41 UTC, imaegg11 commented on core/models/course.py
> +        if self.start_date != None and self.end_date != None and self.start_date > self.end_date:
Yes it shouldn't. Honestly, I don't remember exactly why I added that. However, I do know for a fact that if you fill out the event add form and set either one of the dates to be an invalid one, when you submit it would give you a TypeError due to comparing NoneType and a datetime.datetime. That's probably why I added that when I was testing some things, but I should probably just remove this change.

2024-11-02 19:42 UTC, JasonLovesDoggo commented on core/models/course.py
> +        if self.start_date != None and self.end_date != None and self.start_date > self.end_date:
That's up for handling in the form's logic though, not model's

2024-11-02 19:50 UTC, imaegg11 commented on core/models/course.py
> +        if self.start_date != None and self.end_date != None and self.start_date > self.end_date:
Yea but I was just looking where the error happened and changed that. I'll just remove this change then.

2024-11-04 02:05 UTC, pinwheeeel commented on core/forms.py
> +            self.fields["organization"].initial = models.Organization.objects.get(name='SAC')
You should be querying organizations by [pk](https://docs.djangoproject.com/en/5.1/ref/models/instances/#the-pk-property) instead of name

2024-11-04 02:25 UTC, JasonLovesDoggo commented on core/forms.py
> +            self.fields["organization"].initial = models.Organization.objects.get(name='SAC')
eh, this way is honestly more adaptable as not all db instance will have the same SAC PK... but on this it should be the "School" org 

see https://github.com/wlmac/metropolis/pull/285#issuecomment-2453096088

2024-11-04 02:45 UTC, imaegg11 commented on core/forms.py
> +            self.fields["organization"].initial = models.Organization.objects.get(name='SAC')
What do you mean the "school" organization? Is that not just SAC? Also, for creating a school if it doesn't exist, would you just make the owner and execs just the admin currently using the form?

2024-11-04 16:44 UTC, JasonLovesDoggo commented on core/forms.py
> +            self.fields["organization"].initial = models.Organization.objects.get(name='SAC')
No, there is a school org that is behind something like a late start or an admin related presentation. 

As for the user, just pick the first created superuser (filter by date created and is_superuser).first()

2024-11-06 22:55 UTC, imaegg11 commented
Alright, new commits should have fixed everything. Form is now accessible from the events admin page through a button next to add event.

Screenshot: 
![image](https://github.com/user-attachments/assets/0f15a452-3653-49d0-b6b0-e2cdb35aace5)

2024-11-08 03:14 UTC, pinwheeeel commented
Looks good and works fine 👍

2024-11-11 19:57 UTC, JasonLovesDoggo commented
LGTM!

2024-11-11 19:57 UTC, merged