Daily annoucements
wlmac/metropolis pull request #287
Opened 2024-12-22 22:13 UTC by imaegg11

Back end code for scraping the google sheets using OAuth. Added some google auth libraries and gspread. Also added a command to authorize your google account. 

The scraping is built exactly for the sheet (e.g it takes exactly the 5th cell as the organization name cell), should I change it to a config file or something like that so that its easily changeable? 

Everything works although not sure if I did the dependency files right...

2024-12-22 22:21 UTC, JasonLovesDoggo requested changes
Looks pretty good but there is just a few unresolved TODOs

2024-12-22 22:21 UTC, JasonLovesDoggo commented on core/forms.py
> +        cleaned_data = super().clean()
? this is useless. I assume you forgot to finish this

2024-12-22 22:21 UTC, JasonLovesDoggo commented on core/models/post.py
> +        pass
empty validation method

2024-12-22 22:21 UTC, JasonLovesDoggo commented on core/models/post.py
> +    def get_todays_annoucements(cls) -> QuerySet:
*technically it should be Queryset[Self]

2024-12-22 22:21 UTC, JasonLovesDoggo commented on core/models/post.py
> +        return f"{self.organization} Annoucement"
I would instead have str return data such as self.content[:75]

2024-12-22 22:21 UTC, JasonLovesDoggo commented on core/tasks.py
> +        return
there should be a warning logged in this case

2024-12-22 22:21 UTC, JasonLovesDoggo commented on core/tasks.py
> +    if not Path(settings.SECRETS_PATH).is_dir():
Seems like a good bit of duplicated code between this and the management command, try to refactor into a common method

2024-12-22 22:21 UTC, JasonLovesDoggo commented on metropolis/settings.py
> +GOOGLE_SHEET_KEY = ""
no point adding to global settings

2025-01-15 15:41 UTC, pinwheeeel commented on core/models/post.py
> +class DailyAnnoucement(models.Model):
"Annoucement"?

2025-01-15 16:02 UTC, pinwheeeel commented on core/tasks.py
> +    row_counter = 2
You could a check for the first row with a hard coded value of the column headers to make sure that the columns hasn't been modified

2025-01-15 16:06 UTC, pinwheeeel commented on metropolis/local_settings_sample.py
> +# Daily Annoucment
Double typo :(

2025-01-15 17:10 UTC, imaegg11 commented on core/models/post.py
> +class DailyAnnoucement(models.Model):
English is hard :(

2025-01-15 17:11 UTC, imaegg11 commented on metropolis/local_settings_sample.py
> +# Daily Annoucment
Baguette

2025-01-15 17:14 UTC, imaegg11 commented on core/models/post.py
> +        pass
Fixed

2025-01-15 17:14 UTC, imaegg11 commented on core/models/post.py
> +        return f"{self.organization} Annoucement"
Changed

2025-01-15 17:15 UTC, imaegg11 commented on core/tasks.py
> +        return
Updated to log the warning

2025-01-15 17:15 UTC, imaegg11 commented on metropolis/settings.py
> +GOOGLE_SHEET_KEY = ""
Removed

2025-01-18 03:49 UTC, imaegg11 commented on core/tasks.py
> +    row_counter = 2
Added, see new code

2025-01-18 04:18 UTC, pinwheeeel approved these changes
👍

2025-01-28 01:34 UTC, merged